# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-159814879-3'

menu:
- {name: 'Acerca de', path: 'menu', url: 'about.html'}
- {name: 'Blog', path: 'menu', url: 'writing.html'}
- {name: 'Charlas', path: 'menu', url: 'talks.html'}
- {name: 'Recursos', path: 'menu', url: 'resources.html'}
- {name: 'Contacto', path: 'menu', url: 'contact.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/alexaleg/matmodUNAL2020'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:aleguizamonr@unal.edu.co'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Siguiente'
  previous_page: 'Anterior'

sharing_button_prompt: 'Comparte'

related_posts: 'Te puede interesar'

post_date_prefix: 'Publicado en'
